config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resipes,favorites,impressionsコントローラ
  resources :recipes  do
     resource :favorites, only: %i[create destroy]
     resources :impressions , only: %i[index create destroy]
  end

  # materials,stepsコントローラ
  resources :materials, :steps, only: %i[create update destroy]

  # seachsコントローラ
  resources :seachs, only: [:index]

  # usersコントローラ
  resources :users, only: %i[create update edit show] do
    collection do
      get 'profile'
    end
  end
  
  resources :notifications, only: [:index]
  
end

app/models/impression.rb
class Impression < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  has_many :notifications, dependent: :destroy

  attachment :image

  validates :impression, presence: true, length: { maximum: 50 }
  validates :recipe_id, presence: true
  validates :user_id, presence: true

  def create_notification_impression!(current_user, recipe_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      impression_id: id,
      visitor_id: current_user.id,
      recipe_id: recipe_id.id,
      visited_id: visited_id.id,
      action: 'impression'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/impressions_controller.rb
class ImpressionsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @impression = current_user.impressions.new(impression_params)
    recipe = Recipe.find(params[:recipe_id])
    @impression.recipe_id = recipe.id
    if @impression.recipe.user == current_user
      redirect_to  recipe_path(@impression.recipe)
    else
      if @impression.save
         #通知（modelにメソッド記載）
        @impression.create_notification_impression!(current_user, @impression.recipe,@impression.recipe.user)
        redirect_to recipe_path(recipe), success: "脱レポを投稿しました！"
      else
        redirect_to recipe_path(recipe) , danger: "投稿できませんでした。感想は1文字以上、50文字以内で入力ください"
      end
    end
  end

  def index
    @recipe = Recipe.find(params[:recipe_id])
    @impressions = Impression.includes([:recipe]).includes([:user]).where(recipe: @recipe.id)
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    Impression.find(params[:id]).destroy
    redirect_to recipe_path(recipe), success: "脱レポを削除しました"
  end

  private
  def impression_params
    params.require(:impression).permit(:recipe_id, :user_id, :impression, :image, :reply_comment)
  end
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/views/impressions/_index.html.erb
  <div class="card-group">
     <% @impressions.each do |impression| %>
       <div class="col-3 mt-3">
           <div class="card-impression shadow-sm" style="height:270px;width: 13rem;">
              <%= attachment_image_tag impression, :image,fallback: "cooking.png",class: "card-img-top",style: "height:130px;object-fit:contain;"%>
             <p class="card-text text-center mt-2"><%=impression.impression %></p>
             <p class="card-text text-center profile_image border-0 bg-transparent mb-1">
               <small>by <%=link_to  impression.user.nickname,user_path(impression.user)%></small>
               <%= attachment_image_tag impression.user, :image,fallback: "no-image-icon.png",style: "height: 30px; width:30px; object-fit:contain;"%>
               <br>
               <small><span style="color:gray">投稿日: <%= l impression.created_at %></span></small>
               <% if impression.user == current_user %>
                   <%= link_to "#{icon 'fas', 'trash-alt'}".html_safe, recipe_impression_path(impression.recipe,impression),data: {confirm: '本当に削除しますか？'}, method: :delete %>
               <% end %>
             </p>
           </div>
         </div>
     <% end %>
   </div>

app/views/impressions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 mt-5">
      <h4>脱レポ  <%= @impressions.count %>件</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 mt-3 mb-3">
        <%= render "impressions/index" %>
    </div>
  </div>

    <%= link_to "<< レシピに戻る", recipe_path(@recipe.id) %>
</div>