config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resipes,favorites,impressionsコントローラ
  resources :recipes  do
     resource :favorites, only: %i[create destroy]
     resources :impressions , only: %i[index create destroy]
  end

  # materials,stepsコントローラ
  resources :materials, :steps, only: %i[create update destroy]

  # seachsコントローラ
  resources :seachs, only: [:index]

  # usersコントローラ
  resources :users, only: %i[create update edit show] do
    collection do
      get 'profile'
    end
  end
  
  resources :notifications, only: [:index]
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :recipe_id, presence: true
  validates :user_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_favorite = Favorite.new(user_id: current_user.id, recipe_id: params[:recipe_id])
    if @recipe.user != current_user
      @recipe_favorite.save
      #通知（recipe.rbにメソッド記載）
      @recipe.create_notification_favorite!(current_user)
    else
      redirect_to  recipe_path(@recipe)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_favorite = Favorite.find_by(user_id: current_user.id, recipe_id: params[:recipe_id])
    if @recipe_favorite.user == current_user
      @recipe_favorite.destroy
    else
      redirect_to  recipe_path(@recipe)
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if current_user.favorites.find_by(recipe_id: recipe) %>
           <span style="color:#DBB6C6; font-size:23px;">♥</span>
           <span style="font-size:23px;"><%= @recipe.favorites.count %></span>
          <%=link_to recipe_favorites_path(recipe), method: :delete, remote: true ,class: "btn-sm btn-light ml-3" do %>
          お気に入り解除
          <% end %>
  <% else %>
           <span style="color:#DBB6C6; font-size:23px;">♥</span>
           <span style="font-size:23px;"><%= @recipe.favorites.count %></span>
          <%= link_to recipe_favorites_path(recipe), method: :post, remote: true,class: "btn-sm btn-info ml-3" do %>
          お気に入り登録
          <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @recipe.id %>').html("<%= j(render "favorites/favorite", recipe: @recipe) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @recipe.id %>').html("<%= j(render "favorites/favorite", recipe: @recipe) %>");