config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resipes,favorites,impressionsコントローラ
  resources :recipes  do
     resource :favorites, only: %i[create destroy]
     resources :impressions , only: %i[index create destroy]
  end

  # materials,stepsコントローラ
  resources :materials, :steps, only: %i[create update destroy]

  # seachsコントローラ
  resources :seachs, only: [:index]

  # usersコントローラ
  resources :users, only: %i[create update edit show] do
    collection do
      get 'profile'
    end
  end
  
  resources :notifications, only: [:index]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :materials, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :materials, allow_destroy: true
  has_many :steps, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :steps, allow_destroy: true
  has_many :impression, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :name, presence: true, length: { in: 1..40 }
  validates :introduction, presence: true, length: { in: 1..80 }
  validates :serving, presence: true, numericality: { less_than_or_equal_to: 5 }
  validates :image, presence: true

  attachment :image
  acts_as_taggable # タグ
  
  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and recipe_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        recipe_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
       # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def new
    @recipe = Recipe.new
    @recipe.materials.build
    @recipe.steps.build
  end
  
  def confirm
    @recipe = Recipe.new(recipe_params)
    @materials = @recipe.materials
    @steps =  @recipe.steps
    @tags = @recipe.tag_counts_on(:tags)
    if @recipe.invalid? 
      render :new
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if user_signed_in?
      #byebug
      if @recipe.save
        redirect_to recipe_path(@recipe), success: "レシピを作成しました！"
      else
        render 'new'
        flash[:alart] = "入力内容をご確認ください"
      end
    else
      redirect_to new_user_session_path
    end
  end

  def index
    # お気に入り登録数を多い順に最大5件表示
    @recipe_favorite_ranks = Recipe.includes([:user]).find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(5).pluck(:recipe_id))
    # step数別、新着順にレシピ表示
    @recipe_step_1 = Recipe.includes([:user]).where(steps_count: '1').order(created_at: :desc).page(params[:page]).per(20)
    @recipe_step_2 = Recipe.includes([:user]).where(steps_count: '2').order(created_at: :desc).page(params[:page]).per(20)
    @recipe_step_3 = Recipe.includes([:user]).where(steps_count: '3').order(created_at: :desc).page(params[:page]).per(20)
    @recipe_step_4 = Recipe.includes([:user]).where(steps_count: '4').order(created_at: :desc).page(params[:page]).per(20)
    @recipe_step_5 = Recipe.includes([:user]).where(steps_count: '5').order(created_at: :desc).page(params[:page]).per(20)
    if params[:tag_name] # タグ検索用
      @tag_name = params[:tag_name]
      @tag_recipe = Recipe.tagged_with(params[:tag_name]) # タグに紐付く投稿
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @tags = @recipe.tag_counts_on(:tags)
    @materials = @recipe.materials
    @steps = @recipe.steps
    @impression = @recipe.impression.new
    @impressions = Impression.includes([:recipe]).preload(:user).where(recipe: @recipe.id)
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if current_user != @recipe.user
      redirect_to recipe_path(@recipe)
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      if @recipe.update(recipe_params)
        redirect_to recipe_path(params[:id]), success: "レシピを修正しました！"
      else
        render 'edit', danger: "入力内容をご確認ください"
      end
    else
      redirect_to recipe_path(@recipe)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      redirect_to recipes_path, success: "レシピを削除しました"
    else
      redirect_to recipe_path(@recipe)
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:id, :name, :introduction, :note, :image, :image_id, :user_id, :tag_list, :serving, :steps_count, :tag_name,
                                   steps_attributes: %i[id explanation recipe_id _destroy],
                                   materials_attributes: %i[id name recipe_id quantity _destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_material_fields.html.erb
<div class="nested-fields material-label">
  <div class="row mt-1">
      <div class="field col-sm-5 mt-1"><%= f.text_field :name, placeholder: "材料", class: 'form-control js-material-form' %></div>
      <div class="field col-sm-2 mt-1"><%= f.text_field :quantity, class: "form-control", placeholder: "分量" %></div>
      <div class="field col-sm-1 mt-1">
        <%= link_to_remove_association "#{icon 'fas', 'trash-alt'}".html_safe, f, id: 'remove-btn', data: {confirm: '本当に削除しますか？'},class: "btn btn-outline-secondary" %>
      </div>
  </div>
</div>

app/views/recipes/_recipe_cardgroup.html.erb
<div class="card-group mt-4 mb-4">
  <% recipes.each do |recipe| %>
   <div class="col-3">
     <div class="card shadow-sm">
      <a href="/recipes/<%= recipe.id %>">
       <%= attachment_image_tag recipe, :image, fallback: "no-image-recipe.png", class: 'card-img-top',style: "object-fit:contain;"%>
        <h5 class="card-title text-center  font-weight-bold mt-3"><%= recipe.name%></h5>
          <!---15文字以上は「…」になる（参考記事：https://qiita.com/ishidamakot/items/2e74d980b3a338e4c784)---->
           <p class="card-text text-center mt-2 mb-1"><%= truncate(recipe.introduction, length: 15 ,omission: '…') %></span><br>
           <small>お気に入り登録 <span style="color:#DBB6C6">♥<%= recipe.favorites.count %></span></small>
           </p>
         <p class="card-footer text-center profile_image border-0 bg-transparent"><small>by <%=recipe.user.nickname%></small>
           <%= attachment_image_tag recipe.user, :image, fallback: "no-image-icon.png",style: "height: 30px; width:30px; object-fit:contain;"%>
           <br>
           <small><span style="color:gray">最終更新日: <%= l recipe.updated_at %></span></small>
         </p>
      </div>
    </div>
   <% end %>
  </a>
</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields step-label">
  <div class="row mt-1 ml-1">
      <div class="field col-sm-9 mt-1"><%= f.text_field :explanation, class: "form-control", placeholder: "手順" %></div>
      <div class="field col-sm-1 mt-1">
        <%= link_to_remove_association "#{icon 'fas', 'trash-alt'}".html_safe, f, id: 'remove-btn', data: {confirm: '本当に削除しますか？'},class: "btn btn-outline-secondary" %>
      </div>
  </div>
</div>

app/views/recipes/_tab_content.html.erb
<% if recipe_step.exists? %>
     <%= render "recipes/recipe_cardgroup", recipes: recipe_step %>
  <% else %>
     <p class="text-center mt-5"><i class="fa fa-cutlery" aria-hidden="true"></i> 該当のレシピはありません</p>
<% end %>
<div class="text-center mt-3"><%= paginate recipe_step %></div>

app/views/recipes/confirm.html.erb
    <div class="row">
      <div class="col-sm-6 mt-4">
        <h3><%= @recipe.name%></h3>
      </div>


    <div class="row">
    	<div class="col-sm-3">
      　<div class="recipe_image">
              <%= attachment_image_tag @recipe, :image, fallback: "no-image-recipe.png", style: "height: 230px; width:260px; object-fit:contain;",class:"img-fluid" %>
        </div>
      </div>

      <div class="col-sm-9 mt-3">

          <div class="introduction mt-2">
            <%= @recipe.introduction %>
          </div>
          <div class="tag mt-2 ml-3">
              <% if @tags.present? %>
               <i class="fa fa-tags" aria-hidden="true"></i>
                 <% @tags.each do |tag| %>
                    <%= link_to "＃#{tag.name}", recipes_path(tag_name: tag.name) %>
                  <% end %>
              <% end %>
          </div>
        <div class ="materials mt-3">
            <strong> 材料  <i class="fa fa-male" aria-hidden="true"></i> <%= @recipe.serving %>人前</strong>
              <table class="mt-1">
                <% @materials.each do |material| %>
                <tr>
                <td class="border-bottom border-secondary border-2"><%= material.name %></td>
                <td class="border-bottom border-secondary border-2"><%= material.quantity %></td>
      　         </tr>
      　         <% end %>
      　       </table>
      　</div>
      </div>
   </div>

    <div class="row">
       <div class="col-sm-12 mt-4">
          <h6>作り方</h6>
            <ul class="count_1">
              <% @steps.each do |step|%>
                <li><%= step.explanation %></li>
              <% end %>
            </ul>
        </div>
    </div>

  <% if  @recipe.note.present? %>
    <div class="row">
      <div class="col-sm-7">
        <div class="box">
          <strong><i class="fa fa-hand-o-right" aria-hidden="true"></i> コツ</strong><br>
        　  <%= @recipe.note %>
        </div>
      </div>
    </div>
  <% end %>
 
 
 
 <%= form_with(model: @recipe, local: true, id: "confirm-event") do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :introduction %>
      <%= f.hidden_field :note %>
      <%= f.hidden_field :image %>
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :tag_list %>
      <%= f.hidden_field :serving %>
      <%= f.hidden_field :steps_count %>
      <%= f.hidden_field :explanation %>
      <%= f.hidden_field :recipe_id %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :quantity %>
      <%= f.submit "作成", class: "complete-btn" %>
      <%= f.submit "修正", name: :back, class: "back-btn" %>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
      <div class="row">
      	<div class="col-lg-10 mt-4">
          <h4>レシピ編集</h4>
          </div>
      </div>

          <%= form_with model: @recipe , url: recipe_path ,local: true do |f| %>
           <%= render "layouts/error_messege" , model: f.object %>
        <div class="form-group row form-inline mt-4">
                <%= f.label :name, "レシピ名",class: "col-sm-1 col-form-label" %>

                <%= f.text_field :name, class: "form-control col-sm-8"%>
        </div>

      <div class="row">
        <div class="item-image col-sm-4">
            <%= attachment_image_tag @recipe, :image, class: "img-square img-thumbnail m-1", fallback: "no-image-recipe.png", size: "300x200" %>
            <%= f.attachment_field :image, id: "image"  %>
        </div>

        <div class="col-sm-8 mb-1">
            　<%= f.label :introduction,"料理紹介",class: "col-form-label"%>
            　<%= f.text_area :introduction, class: "form-control col-sm-8"%>
              <%= f.label :tag_list,"タグ" ,class: "col-form-label"%>
              <%= f.text_field :tag_list, value: @recipe.tag_list.join(','), placeholder: "「,」で区切って追加できます。 例)丼ぶり,洗い物なし,即席",class: "form-control col-sm-8"%>
            <!----------材料の項目---------------->
          <div id="materials">
              <%= f.label :serving ,"材料・調味料（最大８種類まで）",class: "col-form-label col-sm-5 mt-3"%>
              <%= f.text_field :serving , class: "col-sm-1" %> 人分
            <!----------材料formの追加ボタン---------------->
            <div class="material-no">
              <div id="add-material">
                <%= link_to_add_association "＋追加",f,:materials,class: "btn-sm btn-info col-1 text-center",
                    data: { association_insertion_method: 'append' }%>
              </div>
            <!----------fields_for----------------%>
                <%= f.fields_for :materials , local: true do |t| %>
            <!----------材料formのテンプレート---------------->
                <%= render "recipes/material_fields", f: t %>
              <% end %>
          </div>
          </div>
        </div>
      </div>

      <div class="form-group row mt-4 mr-1">
        <div class="col-sm-12">
          <div id ="steps">
            <!----------調理手順の項目---------------->
            <div class="col-form-label">作り方（最大5ステップ）</div>
            <!----------調理手順formの追加ボタン---------------->
              <div class="step-no">
                  <%= link_to_add_association "＋追加".html_safe, f, :steps,class: "btn-sm btn-info col-1 text-center",
                    data: { association_insertion_method: 'append'}%>
            <!----------調理手順formを以下に追加---------------->
                   <%= f.fields_for :steps do |t| %>
             <!----------調理手順formのテンプレート---------------->
                    <%= render 'step_fields', f: t %>
                <% end %>
              </div>
          </div>
        </div>
      </div>

      <div class="col-lg-12 mt-3 mb-1">
          <%= f.label :note, "コツ（任意）",class: "col-form-label"%>
          <%= f.text_area :note,class: "form-control col-sm-9" %>
      </div>

      <div class="action col-sm-8 mt-4">
          <%= f.submit "レシピを編集する" ,class: "btn btn-info"%>
          <%= link_to "キャンセル", recipe_path(@recipe) ,class: "btn btn-light ml-3"%>
      </div>
    <% end %>
</div>


<!----画像プレビュー機能--->
  <script>
  $(function() {
      $('#image').on('change', function() {
          var selectedFile = this.files[0];
          var fileReader = new FileReader();

          fileReader.onload = function(event) {
              var loadedImageUri = event.target.result;
               $('.img-square').attr('src', loadedImageUri);
          };

          fileReader.readAsDataURL(selectedFile);
      });
  });
  </script>

app/views/recipes/index.html.erb
<div class="container">
  <!----------タブリンクの結果-------------------------------->
  <% if @tag_recipe.present? %>
      <div class="row">
        <div class="col-lg-12 mt-4">
            <h4><%= "#{@tag_name} に関連するレシピ" %></h4>
               <%= render "recipes/recipe_cardgroup", recipes: @tag_recipe %>
        </div>
      </div>
  <% else %>
  <!---------TOP--------------------------------------------->
    <!----------注目レシピ一覧-------------------------->
    <div class="row">
      <div class="col-lg-12 mt-5">
          <h4>注目レシピ</h4>
          <small>　<i class="fa fa-heart" aria-hidden="true"></i> とくに人気のレシピはこちらです</small>
            <%= render "recipes/recipe_cardgroup", recipes: @recipe_favorite_ranks %>
      </div>
    </div>
    <!----------ステップ数別レシピ一覧-------------------------->
    <div class="row">
        <div class="col-lg-12 mt-5">
          <h4>レシピ一覧</h4>
          <small>　<i class="fa fa-certificate" aria-hidden="true"></i> 料理の手順数別にレシピを見ることができます</small>

            <div class="recipe_tab mt-4">
                <div class="tab-title">
                   <ul class="nav nav-tabs justify-content-center text-center">
                        <li class="recipe_nav-item shadow-m">
                          <a href="#contents0" class="nav-link mr-2" data-toggle="tab">1ステップ</a>
                        </li>                     
                        <li class="recipe_nav-item shadow-m">
                          <a href="#contents1" class="nav-link active mr-2" data-toggle="tab">２ステップ</a>
                        </li>
                        <li class="recipe_nav-item shadow-m">
                          <a href="#contents2" class="nav-link mr-2" data-toggle="tab">３ステップ</a>
                        </li>
                        <li class="recipe_nav-item shadow-m">
                          <a href="#contents3" class="nav-link mr-2" data-toggle="tab">４ステップ</a>
                        </li>
                        <li class="recipe_nav-item shadow-m">
                          <a href="#contents4" class="nav-link mr-2" data-toggle="tab">５ステップ</a>
                        </li>
                    </ul>
                  </div>
              <%#----------タブ内容---------------------------------------------%>
                <div class="tab-content">
                   <%#----------1step-----------------------%>
                    <div id="contents0" class="tab-pane">
                        <%= render "recipes/tab_content", recipe_step: @recipe_step_1 %>
                    </div>
                   <%#----------2step-----------------------%>
                    <div id="contents1" class="tab-pane active">
                        <%= render "recipes/tab_content", recipe_step: @recipe_step_2 %>
                    </div>
                   <%#----------3step-----------------------%>
                    <div id="contents2" class="tab-pane">
                        <%= render "recipes/tab_content", recipe_step: @recipe_step_3 %>
                    </div>
                   <%#----------4step-----------------------%>
                    <div id="contents3" class="tab-pane">
                        <%= render "recipes/tab_content", recipe_step: @recipe_step_4 %>
                    </div>
                  <%#----------5step-----------------------%>
                    <div id="contents4" class="tab-pane">
                        <%= render "recipes/tab_content", recipe_step: @recipe_step_5 %>
                    </div>
                </div>
     　       </div>
        </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container">
      <div class="row">
      	<div class="col-lg-10 mt-4">
          <h4>レシピ投稿</h4>
          </div>
      </div>

          <%= form_with model: @recipe , url: recipes_path ,local: true do |f| %>
              <%= render "layouts/error_messege" , model: f.object%>
              <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group row form-inline mt-4">
                <%= f.label :name, "レシピ名",class: "required mr-4 ml-3 col-form-label" %>
                <%= f.text_field :name, class: "form-control col-sm-8"%>
      </div>

      <div class="row">
        <div class="item-image col-sm-4">
            <%= attachment_image_tag @recipe, :image, class: "img-square img-thumbnail m-1", fallback: "no-image-recipe.png", size: "300x200" %>
            <%= f.attachment_field :image, id: "image" ,class: "required" %>
        </div>

        <div class="col-sm-8 mb-1">
            　<%= f.label :introduction,"料理紹介",class: "required col-form-label"%>
            　<%= f.text_area :introduction, class: "form-control col-sm-8"%>
              <%= f.label :tag_list,"タグ" ,class: "col-form-label"%>
              <%= f.text_field :tag_list, value: @recipe.tag_list.join(','), placeholder: "「,」で区切って追加できます。 例)丼ぶり,洗い物なし,即席",class: "form-control col-sm-8"%>
            <!----------材料の項目---------------->
          <div id="materials">
              <%= f.label :serving ,"材料・調味料（最大８種類まで）",class: "required col-form-label col-sm-5 mt-3"%>
              <span class="required"></span><%= f.text_field :serving , class: "col-sm-1" %> 人分
            <!----------材料formの追加ボタン---------------->
            <div class="material-no">
              <div id="add-material">
                <%= link_to_add_association "＋追加",f,:materials,class: "plus btn-sm btn-info col-1 text-center",
                    data: { association_insertion_method: 'append' }%>
              </div>
            <!----------fields_for----------------%>
                <%= f.fields_for :materials , local: true do |t| %>
            <!----------材料formのテンプレート---------------->
                <%= render "recipes/material_fields", f: t %>
              <% end %>
          </div>
          </div>
        </div>
      </div>

      <div class="form-group row mt-4 mr-1">
        <div class="col-sm-12">
          <div id ="steps">
            <!----------調理手順の項目---------------->
            <div class="col-form-label required">作り方（最大5ステップ）</div>
            <!----------調理手順formの追加ボタン---------------->
              <div class="step-no">
                <div id="add-step">
                  <%= link_to_add_association "＋追加".html_safe, f, :steps,class: "plus btn-sm btn-info col-1 text-center",
                    data: { association_insertion_method: 'append'}%>
                </div>
            <!----------調理手順formを以下に追加---------------->
                   <%= f.fields_for :steps do |t| %>
             <!----------調理手順formのテンプレート---------------->
                    <%= render 'step_fields', f: t %>
                <% end %>
              </div>
          </div>
        </div>
      </div>

      <div class="col-lg-12 mt-3 mb-1">
          <%= f.label :note, "コツ",class: "col-form-label"%>
          <%= f.text_area :note,class: "form-control col-sm-9" %>
      </div>

      <div class="action col-sm-8 mt-4">
          <%= f.submit "レシピを投稿する" ,class: "btn btn-info"%>
          <%= link_to "キャンセル", root_path ,class: "btn btn-light ml-3"%>
      </div>
    <% end %>
</div>


<!----画像プレビュー機能--->
  <script>
  $(function() {
      $('#image').on('change', function() {
          var selectedFile = this.files[0];
          var fileReader = new FileReader();

          fileReader.onload = function(event) {
              var loadedImageUri = event.target.result;
               $('.img-square').attr('src', loadedImageUri);
          };

          fileReader.readAsDataURL(selectedFile);
      });
  });
  </script>

app/views/recipes/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-10 mt-4">
        <% if @recipe.user == current_user %>
          <%= link_to "レシピを編集する", edit_recipe_path(@recipe),class: "btn btn-info ml-3" %>
          <%= link_to "レシピを削除する", recipe_path(@recipe),data: {confirm: '本当に削除しますか？'}, method: :delete,class: "btn btn-danger ml-3" %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6 mt-4">
        <h3><%= @recipe.name%></h3>
      </div>
      <div class="col-sm-3 mt-4 ">
         <% if user_signed_in? && current_user != @recipe.user %>
              <span id="favorite_buttons_<%= @recipe.id %>">
                <%= render "favorites/favorite", recipe: @recipe %>
              </span>
          <% else %>
              <span style="color:#DBB6C6; font-size:23px;">♥</span>
              <span style="font-size:23px;"><%= @recipe.favorites.count %></span>
          <% end %>
      </div>
      <div class="col-sm-3 mt-4">
        <p><small><span style="color:gray">最終更新日: <%= l @recipe.updated_at %></span></small><p>
      </div>
    </div>

    <div class="row">
    	<div class="col-sm-3">
      　<div class="recipe_image">
              <%= attachment_image_tag @recipe, :image, fallback: "no-image-recipe.png", style: "height: 230px; width:260px; object-fit:contain;",class:"img-fluid" %>
        </div>
      </div>

      <div class="col-sm-9 mt-3">
          <div class="recipe-user">
              <%= attachment_image_tag @recipe.user, :image, fallback: "no-image-icon.png",style: "height: 30px; width:30px;"%>
               <small><%=link_to  @recipe.user.nickname,user_path(@recipe.user)%></small>
          </div>
          <div class="introduction mt-2">
            <%= @recipe.introduction %>
          </div>
          <div class="tag mt-2 ml-3">
              <% if @tags.present? %>
               <i class="fa fa-tags" aria-hidden="true"></i>
                 <% @tags.each do |tag| %>
                    <%= link_to "＃#{tag.name}", recipes_path(tag_name: tag.name) %>
                  <% end %>
              <% end %>
          </div>
        <div class ="materials mt-3">
            <strong> 材料  <i class="fa fa-male" aria-hidden="true"></i> <%= @recipe.serving %>人前</strong>
              <table class="mt-1">
                <% @materials.each do |material| %>
                <tr>
                <td class="border-bottom border-secondary border-2"><%= material.name %></td>
                <td class="border-bottom border-secondary border-2"><%= material.quantity %></td>
      　         </tr>
      　         <% end %>
      　       </table>
      　</div>
      </div>
   </div>

    <div class="row">
       <div class="col-sm-12 mt-4">
          <h6>作り方</h6>
            <ul class="count_1">
              <% @steps.each do |step|%>
                <li><%= step.explanation %></li>
              <% end %>
            </ul>
        </div>
    </div>

  <% if  @recipe.note.present? %>
    <div class="row">
      <div class="col-sm-7">
        <div class="box">
          <strong><i class="fa fa-hand-o-right" aria-hidden="true"></i> コツ</strong><br>
        　  <%= @recipe.note %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-12 mt-3">
      <strong>脱レポ 　<i class="fa fa-comment-o" aria-hidden="true"></i> <%= @impressions.count %>件</strong>
        <% if user_signed_in? && current_user != @recipe.user %>
            <button type="button" class="btn btn-info ml-5" data-toggle="modal" data-target="#exampleModal">
              <i class="fa fa-pencil" aria-hidden="true"></i> 脱レポを投稿する
            </button>
        <% end %>
    </div>
    <div class="col-sm-12 mt-3">
        <% if @impressions.exists? %>
            <%= render "impressions/index" %><br>
            <%= link_to ">> 脱レポ一覧へ",recipe_impressions_path(@recipe.id)%>
        <% else %>
             脱レポの投稿はまだありません
        <% end %>
    </div>
    <div class="col-sm-12 mt-3">
        <%= link_to "<< レシピ一覧へ",recipes_path %>
    </div>
  </div>

</div>

  <!-- モーダルの設定 -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">脱レポを投稿</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div><!--/.modal-header -->
        <div class="modal-body">
           <%= form_with model: [@recipe,@impression] , url: recipe_impressions_path(@recipe.id) ,local: true do |f| %>
                <%= f.label :image, "作った料理の画像",class: "col-form-label col-sm-12"%>
              <%= attachment_image_tag @impression, :image, class: "img-square img-thumbnail m-1", fallback: "cooking.png", size: "200x150" %>
              <%= f.attachment_field :image, id: "image"  %>
              <%= f.label :impression, "感想",class: "required col-form-label mt-2 col-12"%>
              <%= f.text_area :impression, placeholder: "必須です。50文字以内で入力ください。",class: "form-control col-sm-12 mb-3"%>
              <%= f.submit "脱レポを送る" ,class: "btn btn-info col-sm-6"%>
        </div>
        <div class="modal-footer">
              <%= link_to "キャンセル", recipe_path(@recipe),class: "btn btn-light ml-3"%>
            <% end %>
        </div><!-- /.modal-footer -->
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>

  <script>
    $(function() {
        $('#image').on('change', function() {
            var selectedFile = this.files[0];
            var fileReader = new FileReader();

            fileReader.onload = function(event) {
                var loadedImageUri = event.target.result;
                 $('.img-square').attr('src', loadedImageUri);
            };

            fileReader.readAsDataURL(selectedFile);
        });
    });
  </script>