config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resipes,favorites,impressionsコントローラ
  resources :recipes  do
     resource :favorites, only: %i[create destroy]
     resources :impressions , only: %i[index create destroy]
  end

  # materials,stepsコントローラ
  resources :materials, :steps, only: %i[create update destroy]

  # seachsコントローラ
  resources :seachs, only: [:index]

  # usersコントローラ
  resources :users, only: %i[create update edit show] do
    collection do
      get 'profile'
    end
  end
  
  resources :notifications, only: [:index]
  
end

app/views/layouts/_error_messege.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
    <% flash.each do |key, value| %>
      <% key = "success" if key == "notice" %>
      <% key = "danger"  if key == "alert" %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>

app/views/layouts/_footer.html.erb
<footer>
   <div class="container">
      <div class="logo m-2">
            <%= link_to root_path do %>
            <%= image_tag 'footer_logo.png', :size =>'120x40', class: "d-block mx-auto" %>
            <% end %>
    </div>
  <p class="text-center"><small>© 2022.02~ OshimaYuki</small></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="border">
 <div class="hed pl-1">手間と時間をかけないレシピがここにある</div>
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand p-3">
          <%= link_to root_path do %>
           <%= image_tag 'logo.png', :size =>'140x100'%>
          <% end %>
        </a>

        <div class="navbar-nav ml-auto mt-3">
         <div class="nav-item-search">
          <%= search_form_for @search , url: seachs_path do |f| %>
           <%= f.search_field :name_cont, placeholder: "レシピ名を検索", class: "search_input p-3"%>
            <%= f.button :type => "submit",  :class => "search_submit" do %>
              <i class="fa fa-search" aria-hidden="true"></i>
            <% end %>
          <% end %>
         </div>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
         <span class="navbar-toggler-icon"><i class="fa fa-bars" aria-hidden="true"></i></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

           <% if user_signed_in? %>
           <ul>
             <li class="nav-item">
               <%= link_to "レシピ投稿", new_recipe_path,class: "mx-4 my-1 mr-4" %>
             </li>
             <li class="nav-item">
               <%= link_to "マイページ", "/users/#{current_user.id}",class: "mx-4 my-1 mr-4" %>
             </li>
             <li class="nav-item notify mx-4 my-1 mr-4">
               <%= render partial: 'notifications/index',remote: true %>
             </li>
            </ul>
         <% else %>
            <ul>
             <li class="nav-item">
               <%= link_to "新規登録", new_user_registration_path,class: "mx-4 my-1 mr-4"  %>
             </li>
             <li class="nav-item">
               <%= link_to "ログイン", new_user_session_path ,class: "mx-4 my-1 mr-4"%>
             </li>
            </ul>
          <% end %>

      </div>
     </div>
    </nav>
  </header>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>脱力レシピ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c3fbb4b704.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <!-- Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div id="wrapper">
        <%= render "layouts/header"%>
    </div>
    <main>
     <div id="flash">
        <%= render "layouts/flash" %>
     </div>
     <div id="notify-modal" class="modal notify-modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
      <%= yield %>
    </main>
    <div class="footerFixed">　<%#CSSでフッター位置の調整%>
    <%= render "layouts/footer"%>
  </div>
  </body>
</html>